# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# @feature: mysql-slowsql; mysqld configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slowsql-mysql-cnf
  labels:
    app: slowsql-mysql-cnf
data:
  config-file: |
    [mysqld]
    init_connect='SET NAMES utf8'
    slow_query_log=ON
    event_scheduler=ON
    long_query_time=1
    slow_query_log_file=/data/slow.log
    [client]
    default-character-set=utf8
    [mysql]
    default-character-set=utf8

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-sql-mysql-slowsql
  labels:
    app: mysql-load
data:
  mock-sql: |
    CREATE DATABASE IF NOT EXISTS test;
    USE test;
    CREATE TABLE IF NOT EXISTS `t1`(
       `te1` VARCHAR(100) NOT NULL
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;
    SET GLOBAL event_scheduler = 1;

    CREATE EVENT `event_1`
    ON SCHEDULE EVERY 1 SECOND
    DO INSERT INTO t1 values('test');

    CREATE EVENT `event_2`
    ON SCHEDULE EVERY 1 SECOND
    DO UPDATE t1 SET `te1` = 1;

    CREATE EVENT `event_3`
    ON SCHEDULE EVERY 1 SECOND
    DO DELETE FROM t1;

    CREATE EVENT `event_4`
    ON SCHEDULE EVERY 1 SECOND
    DO COMMIT;

    CREATE EVENT `event_5`
    ON SCHEDULE EVERY 1 SECOND
    DO SELECT SLEEP(3);

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slowsql
spec:
  selector:
    app: mysql-slowsql
  ports:
    - protocol: TCP
      port: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-slowsql
  labels:
    app: mysql-slowsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slowsql
  template:
    metadata:
      labels:
        app: mysql-slowsql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.30
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: slowsql-mysql-cnf
              mountPath: /etc/mysql/conf.d/config-file.cnf
              subPath: config-file
            - name: slowsql-mysql-data
              mountPath: /data
      volumes:
        - name: slowsql-mysql-cnf
          configMap:
            name: slowsql-mysql-cnf
        - name: slowsql-mysql-data
          persistentVolumeClaim:
            claimName: slowsql-mysql-pvc

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-load-deployment-slowsql # @feature: mysql-slowsql; set up job to trigger mysql slow commands, you don't need this in production env.
spec:
  template:
    metadata:
      name: mysql-load-deployment-slowsql
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:  ["sh", "-c", "until nc -z mysql-slowsql 3306 > /dev/null; do echo Waiting for mysql-slowsql.; sleep 2; done;"]
      containers:
        - name: mysql-load-slowsql
          image: mysql:8.0.30
          command:
            - bash
            - -c
            - mysql -hmysql-slowsql -uroot -ppassword < /conf/mock.sql
          volumeMounts:
            - name: mock-sql-vol-mysql-slowsql
              mountPath: /conf
      volumes:
        - name: mock-sql-vol-mysql-slowsql
          configMap:
            name: mock-sql-mysql-slowsql
            items:
              - key: mock-sql
                path: mock.sql
