{
 "title": "General Relation",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "layer", "label": "Layer", "query": "GENERAL" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(service_traffic{layer='$layer'}, service)"
    }
   },
   {
    "name": "service_instance",
    "label": "Service Instance",
    "query": {
     "query": "label_values(instance_traffic{layer='$layer', service='$service'}, service_instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(endpoint_traffic{layer='$layer', service='$service', keyword='$endpoint_keyword', limit='$endpoint_limit'}, endpoint)"
    }
   },
   { "name": "endpoint_keyword", "label": "Endpoint Keyword" },
   { "name": "endpoint_limit", "label": "Endpoint Limit", "query": "20,50,100" },
   { "name": "DS_SW_Prometheus", "query": "prometheus" },
   {
    "name": "dest_service",
    "label": "Dest Service",
    "query": {
     "query": "label_values(service_traffic{layer=\"$dest_layer\"},service)"
    }
   },
   {
    "name": "dest_service_instance",
    "label": "Dest Service Instance",
    "query": {
     "query": "label_values(instance_traffic{layer=\"$dest_layer\", service=\"$dest_service\"},service_instance)"
    }
   },
   {
    "name": "dest_endpoint",
    "label": "Dest Endpoint",
    "query": {
     "query": "label_values(endpoint_traffic{layer=\"$dest_layer\", service=\"$dest_service\", keyword=\"$endpoint_keyword\", limit=\"$endpoint_limit\"},endpoint)"
    }
   },
   { "name": "dest_layer", "label": "Dest Layer", "query": "GENERAL" }
  ]
 },
 "panels": [
  { "title": "Service Relation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load (Client) (calls / min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "service_relation_client_cpm{service='$service', dest_service='$dest_service', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Load (Server) (calls / min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "service_relation_server_cpm{service='$service', dest_service='$dest_service', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Success Rate (Client) (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "service_relation_client_call_sla{service='$service', dest_service='$dest_service', layer='$layer', dest_layer='$dest_layer'} / 100",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Success Rate (Server) (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "service_relation_server_call_sla{service='$service', dest_service='$dest_service', layer='$layer', dest_layer='$dest_layer'} / 100",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Response Time (Client) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "service_relation_client_resp_time{service='$service', dest_service='$dest_service', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Response Time (Server) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "service_relation_server_resp_time{service='$service', dest_service='$dest_service', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Response Time Percentile (Client) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "service_relation_client_percentile{service=\"$service\", dest_service=\"$dest_service\", layer=\"$layer\", dest_layer=\"$dest_layer\",p=\"50,75,90,95,99\"}",
     "legendFormat": "{{p}}"
    }
   ]
  },
  {
   "title": "Response Time Percentile (Server) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "service_relation_server_percentile{service=\"$service\", dest_service=\"$dest_service\", layer=\"$layer\", dest_layer=\"$dest_layer\",p=\"50,75,90,95,99\"}",
     "legendFormat": "{{p}}"
    }
   ]
  },
  { "title": "Service Instance Relation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Load (Client) (calls / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "service_instance_relation_client_cpm{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Load (Server) (calls / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "service_instance_relation_server_cpm{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Success Rate (Client) (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "service_instance_relation_client_call_sla{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer'}/100",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Success Rate (Server) (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "service_instance_relation_server_call_sla{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer'}/100",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Response Time (Client) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "service_instance_relation_client_resp_time{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Response Time (Server) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "service_instance_relation_server_resp_time{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Response Time Percentile (Client) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "service_instance_relation_client_percentile{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer',p=\"50,75,90,95,99\"}",
     "legendFormat": "{{ p }}"
    }
   ]
  },
  {
   "title": "Response Time Percentile (Server) (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    {
     "expr": "service_instance_relation_server_percentile{service='$service', dest_service='$dest_service', service_instance='$service_instance', dest_service_instance='$dest_service_instance', layer='$layer', dest_layer='$dest_layer',p=\"50,75,90,95,99\"}",
     "legendFormat": "{{ p }}"
    }
   ]
  },
  { "title": "Endpoint Relation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Load (calls / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "endpoint_relation_cpm{service='$service', dest_service='$dest_service', endpoint='$endpoint', dest_endpoint='$dest_endpoint', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Success Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "endpoint_relation_sla{service='$service', dest_service='$dest_service', endpoint='$endpoint', dest_endpoint='$dest_endpoint', layer='$layer', dest_layer='$dest_layer'}/100",
     "legendFormat": "success_rate"
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "endpoint_relation_resp_time{service='$service', dest_service='$dest_service', endpoint='$endpoint', dest_endpoint='$dest_endpoint', layer='$layer', dest_layer='$dest_layer'}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "Service Response Time Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "endpoint_relation_percentile{service='$service', dest_service='$dest_service', endpoint='$endpoint', dest_endpoint='$dest_endpoint', layer='$layer', dest_layer='$dest_layer',p='50,75,90,95,99'}",
     "legendFormat": "{{ p }}"
    }
   ]
  }
 ]
}