{
 "title": "General Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "layer", "label": "Layer", "query": "GENERAL" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(service_traffic{layer='$layer'}, service)"
    }
   },
   {
    "name": "service_instance",
    "label": "Service Instance",
    "query": {
     "query": "label_values(instance_traffic{layer='$layer', service='$service'}, service_instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(endpoint_traffic{layer='$layer', service='$service', keyword='$endpoint_keyword', limit='$endpoint_limit'}, endpoint)"
    }
   },
   { "name": "endpoint_keyword", "label": "Endpoint Keyword" },
   { "name": "endpoint_limit", "label": "Endpoint Limit", "query": "20,50,100" },
   { "name": "DS_SW_Prometheus", "query": "prometheus" },
   { "name": "Plugin_SkyWalking", "query": "apache-skywalking-datasource" }
  ]
 },
 "panels": [
  { "title": "Service Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "edgeMetrics": "[   {     \"name\": \"service_relation_server_cpm\",     \"label\": \"Server Load\",     \"unit\": \"cpm\",     \"type\": \"SERVER\"   },   {     \"name\": \"service_relation_server_resp_time\",     \"label\": \"Server Latency\",     \"unit\": \"ms\",     \"type\": \"SERVER\"   },   {     \"name\": \"service_relation_client_cpm\",     \"label\": \"Client Load\",     \"unit\": \"cpm\",     \"type\": \"CLINET\"   },   {     \"name\": \"service_relation_client_resp_time\",     \"label\": \"Client Latency\",     \"unit\": \"ms\",     \"type\": \"CLINET\"   } ]",
     "layer": "$layer",
     "nodeMetrics": "[   {     \"name\": \"service_cpm\",     \"label\": \"Load\",     \"unit\": \"cpm\"   },   {     \"name\": \"service_sla\",     \"calculation\": \"percentage\",     \"label\": \"Success Rate\",     \"unit\": \"%\"   },   {     \"name\": \"service_resp_time\",     \"label\": \"Latency\",     \"unit\": \"ms\"   },   {     \"name\": \"service_apdex\",     \"label\": \"Apdex\",     \"calculation\": \"apdex\"   } ]"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Service Apdex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_apdex{service='$service', layer='$layer'} / 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_sla{service='$service', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_cpm{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_resp_time{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Apdex",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_apdex{service='$service', layer='$layer'} / 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Response Time Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_percentile{service='$service', layer='$layer', labels='0,1,2,3,4', relabels='P50,P75,P90,P95,P99'}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Service Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "service_cpm{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_sla{service='$service', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Queue Consuming Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_mq_consume_count{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Queue Avg Consuming Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_mq_consume_latency{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Instances Load ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_instance_cpm{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Slow Service Instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_instance_resp_time{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Service Instance Success Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_instance_sla{parent_service='$service', layer='$layer', top_n='10', order='DES'} / 100",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Endpoint Load in Current Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_cpm{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Slow Endpoints in Current Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_resp_time{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Success Rate in Current Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_sla{parent_service='$service', layer='$layer', top_n='10', order='DES'} / 100",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Service Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Instance Load ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "service_instance_cpm{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Instance Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "service_instance_sla{service='$service', service_instance='$service_instance', layer='$layer'} / 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Instance Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "service_instance_resp_time{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Database Connection Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "meter_datasource{service='$service', service_instance='$service_instance', layer='$layer'} / 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "meter_thread_pool{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Service Instance JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "JVM CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance_jvm_cpu{service='$service', service_instance='$service_instance',layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "instance_jvm_memory_noheap_max{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_memory_noheap{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_memory_heap{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_memory_heap_max{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "instance_jvm_young_gc_time{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_old_gc_time{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_normal_gc_time{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance_jvm_young_gc_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_old_gc_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_normal_gc_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance_jvm_thread_live_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_thread_daemon_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_thread_peak_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Thread State Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance_jvm_thread_timed_waiting_state_thread_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_thread_blocked_state_thread_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_thread_waiting_state_thread_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_thread_runnable_state_thread_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Class Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "instance_jvm_class_loaded_class_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_class_total_loaded_class_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    },
    {
     "expr": "instance_jvm_class_total_unloaded_class_count{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Endpoint Load ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "endpoint_cpm{service='$service', endpoint='$endpoint', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "endpoint_resp_time{endpoint='$endpoint', service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Response Time Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "endpoint_percentile{service='$service', endpoint=\"$endpoint\", layer='$layer', labels='0,1,2,3,4', relabels='P50,P75,P90,P95,P99'}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Endpoint Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "endpoint_sla{service='$service', endpoint='$endpoint', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Queue Avg Consuming Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_mq_consume_latency{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}