{
 "title": "Service Mesh",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "layer", "label": "Layer", "query": "MESH" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(service_traffic{layer='$layer'}, service)"
    }
   },
   {
    "name": "service_instance",
    "label": "Service Instance",
    "query": {
     "query": "label_values(instance_traffic{layer='$layer', service='$service'}, service_instance)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(endpoint_traffic{layer='$layer', service='$service', keyword='$endpoint_keyword', limit='$endpoint_limit'}, endpoint)"
    }
   },
   { "name": "endpoint_keyword", "label": "Endpoint Keyword" },
   { "name": "endpoint_limit", "label": "Endpoint Limit", "query": "20,50,100" },
   { "name": "DS_SW_Prometheus", "query": "prometheus" },
   { "name": "Plugin_SkyWalking", "query": "apache-skywalking-datasource" }
  ]
 },
 "panels": [
  { "title": "Service Topology", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "edgeMetrics": "[   {     \"name\": \"service_relation_server_cpm\",     \"label\": \"Server Load\",     \"unit\": \"cpm\",     \"type\": \"SERVER\"   },   {     \"name\": \"service_relation_server_resp_time\",     \"label\": \"Server Latency\",     \"unit\": \"ms\",     \"type\": \"SERVER\"   },   {     \"name\": \"service_relation_client_cpm\",     \"label\": \"Client Load\",     \"unit\": \"cpm\",     \"type\": \"CLINET\"   },   {     \"name\": \"service_relation_client_resp_time\",     \"label\": \"Client Latency\",     \"unit\": \"ms\",     \"type\": \"CLINET\"   } ]",
     "layer": "$layer",
     "nodeMetrics": "[   {     \"name\": \"service_cpm\",     \"label\": \"Load\",     \"unit\": \"cpm\"   },   {     \"name\": \"service_sla\",     \"calculation\": \"percentage\",     \"label\": \"Success Rate\",     \"unit\": \"%\"   },   {     \"name\": \"service_resp_time\",     \"label\": \"Latency\",     \"unit\": \"ms\"   },   {     \"name\": \"service_apdex\",     \"label\": \"Apdex\",     \"calculation\": \"apdex\"   } ]"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Service Apdex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_apdex{service='$service', layer='$layer'} / 10000",
     "legendFormat": "apdex"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_sla{service='$service', layer='$layer'} / 100",
     "legendFormat": "sla"
    }
   ]
  },
  {
   "title": "Service Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_cpm{service='$service', layer='$layer'}",
     "legendFormat": "cpm"
    }
   ]
  },
  {
   "title": "Service Apdex",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_apdex{service='$service', layer='$layer'}",
     "legendFormat": "apdex"
    }
   ]
  },
  {
   "title": "Service Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_resp_time{service='$service', layer='$layer'}",
     "legendFormat": "resp_time"
    }
   ]
  },
  {
   "title": "Service Response Time Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_percentile{service='$service', layer='$layer', p='50,75,90,95,99'}",
     "legendFormat": "{{p}}"
    }
   ]
  },
  {
   "title": "Success Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_sla{service='$service', layer='$layer'} / 100",
     "legendFormat": "sla"
    }
   ]
  },
  {
   "title": "Service Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "service_cpm{service='$service', layer='$layer'}",
     "legendFormat": "cpm"
    }
   ]
  },
  {
   "title": "Service Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "service_throughput_received{service='$service', layer='$layer'}",
     "legendFormat": "received"
    },
    {
     "expr": "service_throughput_sent{service='$service', layer='$layer'}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Service Instances Load ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_instance_cpm{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Slow Service Instance",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_instance_resp_time{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Service Instance Success Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_instance_sla{parent_service='$service', layer='$layer', top_n='10', order='DES'} / 100",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Endpoint Load in Current Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_cpm{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Slow Endpoints in Current Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_resp_time{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Success Rate in Current Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_sla{parent_service='$service', layer='$layer', top_n='10', order='DES'} / 100",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "service_sidecar_internal_req_latency_nanos{service='$service', layer='$layer'}",
     "legendFormat": "latency_nanos"
    }
   ]
  },
  {
   "title": "Proxy Sidecar Internal Latency (Response)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "service_sidecar_internal_resp_latency_nanos{service='$service', layer='$layer'}",
     "legendFormat": "latency_nanos"
    }
   ]
  },
  { "title": "Service Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Service Instance Load ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "service_instance_cpm{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "cpm"
    }
   ]
  },
  {
   "title": "Service Instance Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "service_instance_throughput_received{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "received"
    },
    {
     "expr": "service_instance_throughput_sent{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Service Instance Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_instance_sla{service='$service', service_instance='$service_instance', layer='$layer'} / 100",
     "legendFormat": "sla"
    }
   ]
  },
  {
   "title": "Service Instance Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "service_instance_resp_time{service='$service', service_instance='$service_instance', layer='$layer'}",
     "legendFormat": "resp_time"
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "Endpoint Load ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "endpoint_cpm{service='$service', endpoint='$endpoint', layer='$layer'}",
       "legendFormat": "cpm"
      }
     ]
    },
    {
     "title": "Endpoint Avg Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "endpoint_resp_time{endpoint='$endpoint', service='$service', layer='$layer'}",
       "legendFormat": "resp_time"
      }
     ]
    },
    {
     "title": "Endpoint Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "endpoint_sla{service='$service', endpoint='$endpoint', layer='$layer'} / 100",
       "legendFormat": "sla"
      }
     ]
    },
    {
     "title": "Endpoint Response Time Percentile",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "endpoint_percentile{service='$service', endpoint=\"$endpoint\", layer='$layer', p='50,75,90,95,99'}",
       "legendFormat": "{{p}}"
      }
     ]
    },
    {
     "title": "Proxy Sidecar Internal Latency (Request)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "endpoint_sidecar_internal_req_latency_nanos{service='$service', endpoint='$endpoint', layer='$layer'}",
       "legendFormat": "latency_nanos"
      }
     ]
    },
    {
     "title": "Proxy Sidecar Internal Latency (Response)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "endpoint_sidecar_internal_resp_latency_nanos{service='$service', endpoint='$endpoint', layer='$layer'}",
       "legendFormat": "latency_nanos"
      }
     ]
    }
   ]
  },
  {
   "title": "Envoy Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Used ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "envoy_memory_allocated_max{service='$service', service_instance='$service_instance',layer='$layer'}",
       "legendFormat": "envoy_memory_allocated_max"
      },
      {
       "expr": "envoy_heap_memory_used{service='$service', service_instance='$service_instance',layer='$layer'}",
       "legendFormat": "envoy_heap_memory_used"
      },
      {
       "expr": "envoy_memory_allocated{service='$service', service_instance='$service_instance',layer='$layer'}",
       "legendFormat": "envoy_memory_allocated"
      },
      {
       "expr": "envoy_memory_physical_size{service='$service', service_instance='$service_instance',layer='$layer'}",
       "legendFormat": "envoy_memory_physical_size"
      },
      {
       "expr": "envoy_memory_physical_size_max{service='$service', service_instance='$service_instance',layer='$layer'}",
       "legendFormat": "envoy_memory_physical_size_max"
      },
      {
       "expr": "envoy_heap_memory_max_used{service='$service', service_instance='$service_instance',layer='$layer'}",
       "legendFormat": "envoy_heap_memory_max_used"
      }
     ]
    },
    {
     "title": "Connections Used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_total_connections_used{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "envoy_total_connections_used"
      },
      {
       "expr": "envoy_parent_connections_used{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "envoy_parent_connections_used"
      }
     ]
    },
    {
     "title": "Concurrency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_worker_threads_max{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "envoy_worker_threads_max"
      },
      {
       "expr": "envoy_worker_threads{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "envoy_worker_threads"
      }
     ]
    },
    {
     "title": "Envoy Bug Failure",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_bug_failures{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "Membership Healthy",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_cluster_membership_healthy{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Connection Active",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_cluster_up_cx_active{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Connection Increase ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "envoy_cluster_up_cx_incr{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Request Active",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_cluster_up_rq_active{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Request Increase",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "envoy_cluster_up_rq_incr{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Upstream Request Pending Active",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "envoy_cluster_up_rq_pending_active{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "{{cluster_name}}"
      }
     ]
    },
    {
     "title": "Proxy Sidecar Internal Latency (Request)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "service_instance_sidecar_internal_req_latency_nanos{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "latency_nanos"
      }
     ]
    },
    {
     "title": "Proxy Sidecar Internal Latency (Response)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "service_instance_sidecar_internal_resp_latency_nanos{service='$service', service_instance='$service_instance', layer='$layer'}",
       "legendFormat": "latency_nanos"
      }
     ]
    }
   ]
  }
 ]
}