{
 "title": "Virtual-Database",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "layer", "query": "VIRTUAL_DATABASE" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(service_traffic{layer='$layer'}, service)"
    }
   },
   { "name": "DS_SkyWalking", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Database Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "database_access_resp_time{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Access Successful Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "database_access_sla{service='$service', layer='$layer'} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "database_access_cpm{service='$service', layer='$layer'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Access Latency Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "database_access_percentile{service='$service', layer='$layer', labels='0,1,2,3,4', relabels='P50,P75,P90,P95,P99'}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Slow Statements ",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "top_n_database_statement{parent_service='$service', layer='$layer', top_n='10', order='DES'}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}