# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: skywalking-oap-sa

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skywalking-oap-sa-role
rules:
  - apiGroups: [ "" ]
    resources:
      - "pods" # @feature: als; OAP needs to read pods metadata to analyze the access logs
      - "pods/log" # @feature: on-demand-pod-logs; in feature on demand Pod logs, OAP needs to read pods logs
      - "services" # @feature: als; OAP needs to read services metadata to analyze the access logs
      - "endpoints" # @feature: als; OAP needs to read endpoints metadata to analyze the access logs
      - "nodes" # @feature: als; OAP needs to read nodes metadata to analyze the access logs
      - "configmaps"
    verbs: [ "get", "watch", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skywalking-oap-sa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skywalking-oap-sa-role
subjects:
  - kind: ServiceAccount
    name: skywalking-oap-sa
    namespace: ${NAMESPACE}
