# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '2.1'

services:
  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile.nginx
    volumes:
      - ./config/nginx/nginx.conf:/var/nginx/conf.d/nginx.conf
      - /tmp/skywalking-logs/nginx:/var/log/nginx
    entrypoint: ['bash', '-c', 'openresty -c /var/nginx/conf.d/nginx.conf']
    depends_on:
      oap:
        condition: service_healthy
    ports:
      - 8080
    expose:
      - 9145
    networks:
      - sw

  nginx-caller:
    image: openresty/openresty:1.17.8.2-5-alpine-fat
    depends_on:
      - otel-collector
    networks:
      - sw
    entrypoint: sh
    command:
      - -c
      - "while true; do curl -o /dev/null -s http://nginx:8080/test; curl -o /dev/null -s http://nginx:8080/test_404; curl -o /dev/null -s http://nginx:8080/test_500; sleep 1s; done"

  fluent-bit:
    image: fluent/fluent-bit:1.9
    volumes:
      - /tmp/skywalking-logs/nginx:/var/log/nginx
      - ./config/nginx/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/nginx/fluent-bit-script.lua:/fluent-bit/etc/fluent-bit-script.lua
    depends_on:
      - oap
      - nginx
    networks:
      - sw

  otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE}:${OTEL_COLLECTOR_IMAGE_TAG}
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./config/nginx/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - oap
      - nginx
    expose:
      - 55678
    networks:
      sw:

networks:
  sw:
