# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
apiVersion: v1
kind: Service
metadata:
  name: satellite
spec:
  selector:
    app: satellite
  ports:
    - name: grpc
      port: 11800

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite-deployment
  labels:
    app: satellite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellite
  template:
    metadata:
      labels:
        app: satellite
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: skywalking-satellite-sa
      containers:
        - name: satellite
          image: ${SW_SATELLITE_IMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: "512Mi"
            requests:
              cpu: 500m
              memory: "512Mi"
          ports:
            - name: grpc
              containerPort: 11800
          env:
            - name: SATELLITE_GRPC_CLIENT_FINDER
              value: kubernetes
            - name: SATELLITE_GRPC_CLIENT_KUBERNETES_NAMESPACE
              value: ${NAMESPACE}
            - name: SATELLITE_GRPC_CLIENT_KUBERNETES_KIND
              value: pod
            - name: SATELLITE_GRPC_CLIENT_KUBERNETES_SELECTOR_LABEL
              value: app=oap
            - name: SATELLITE_GRPC_CLIENT_KUBERNETES_EXTRA_PORT
              value: "11800"
            - name: SATELLITE_TELEMETRY_EXPORT_TYPE
              value: metrics_service